# permissions for end users to view dayzs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dayz-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gameserver-operator
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: dayz-viewer-role
rules:
  - apiGroups:
      - gameserver.templarfelix.com
    resources:
      - dayzs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - gameserver.templarfelix.com
    resources:
      - dayzs/status
    verbs:
      - get
