# permissions for end users to view projectzomboids.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: projectzomboid-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gameserver-operator
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
  name: projectzomboid-viewer-role
rules:
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - projectzomboids
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - projectzomboids/status
  verbs:
  - get
