---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - dayzs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - dayzs/finalizers
  verbs:
  - update
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - dayzs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - projectzomboids
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - projectzomboids/finalizers
  verbs:
  - update
- apiGroups:
  - gameserver.templarfelix.com
  resources:
  - projectzomboids/status
  verbs:
  - get
  - patch
  - update
