apiVersion: gameserver.templarfelix.com/v1alpha1
kind: Dayz
metadata:
  labels:
    app.kubernetes.io/name: dayz
    app.kubernetes.io/instance: dayz-sample
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gameserver-operator
  name: dayz-sample
spec:
  # TODO(user): Add fields here
