apiVersion: gameserver.templarfelix.com/v1alpha1
kind: ProjectZomboid
metadata:
  labels:
    app.kubernetes.io/name: projectzomboid
    app.kubernetes.io/instance: projectzomboid-sample
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gameserver-operator
  name: projectzomboid-sample
spec:
# TODO(user): Add fields here
