apiVersion: gameserver.templarfelix.com/v1alpha1
kind: Dayz
metadata:
  labels:
    app.kubernetes.io/name: dayz
    app.kubernetes.io/instance: dayz-sample
    app.kubernetes.io/part-of: gameserver-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gameserver-operator
  name: dayz-sample
spec:
  storage: 10G
  #loadBalancerIP:
  ports:
    - name: port-27015-tcp
      port: 27015
      targetPort: 27015
      protocol: TCP
    - name: port-27016-tcp
      port: 27016
      targetPort: 27016
      protocol: TCP
    - name: port-2302-udp
      port: 2302
      targetPort: 2302
      protocol: UDP
    - name: port-2304-udp
      port: 2304
      targetPort: 2304
      protocol: UDP
    - name: port-2306-udp
      port: 2306
      targetPort: 2306
      protocol: UDP
    - name: port-27015-udp
      port: 27015
      targetPort: 27015
      protocol: UDP
    - name: port-27016-udp
      port: 27016
      targetPort: 27016
      protocol: UDP
  config:
    # dayz server config
    server: |
      // ****************************************************************************
      //                                                                            *
      //     DayZ - server.cfg                                                      *
      //     Version 090921                                                         *
      //                                                                            *
      // ****************************************************************************
  
      // DayZ Server Config File
      //
      // More info about parameters:
      // https://community.bistudio.com/wiki/DayZ:Server_Configuration
  
      // GENERAL SETTINGS
  
      // Server name
      hostname = "gameserver-operator";
  
      // Password to connect to the server
      //password = "";
  
      // Password to become a server admin
      passwordAdmin = "changeme";
  
      // Enable/disable whitelist (value 0-1)
      enableWhitelist = 0;
  
      // Maximum amount of players
      maxPlayers = 60;
  
      // Saves the server console log to a file in the folder with the other server logs
      // This variable can crash server on early dayz experimental linux builds
      //logFile = "server_console.log";
  
      // Defines Steam query port, should fix the issue with server not being visible in client server browser
      // If you are host multiple instances, you can use 2305 (game port + 3)
      steamQueryPort = 27016;
  
      // INGAME SETTINGS
  
      // Enable/disable voice over network (value 0-1)
      disableVoN = 0;
  
      // Voice over network codec quality, the higher the better (values 0-30)
      vonCodecQuality = 20;
  
      // Toggles the 3rd person view for players (value 0-1)
      disable3rdPerson = 0;
  
      // Toggles the cross-hair (value 0-1)
      disableCrosshair = 0;
  
      // 0 for brighter night, 1 for darker night
      lightingConfig = 0;
  
      // disables personal light for all clients connected to server
      disablePersonalLight = 0;
  
      // Message of the day displayed in the in-game chat
      motd[] = {
          "Welcome to My DayZ Server",
          "TS3 Server:     teamspeak.somewhere.com",
          "Web:            www.example.com"
      };
  
      // Time interval (in seconds) between each message
      motdInterval = 60;
  
      // Initial in-game time of the server. "SystemTime" means the local time of the machine. Another possibility is to set the time to some value in "YYYY/MM/DD/HH/MM" format, e.g "2015/4/8/17/23".
      serverTime = "SystemTime";
  
      // Accelerated Time - The numerical value being a multiplier (0.1-64). Thus, in case it is set to 24, time would move 24 times faster than normal. An entire day would pass in one hour.
      serverTimeAcceleration = 1;
  
      // Accelerated Nigh Time - The numerical value being a multiplier (0.1-64) and also multiplied by serverTimeAcceleration value.
      // Thus, in case it is set to 4 and serverTimeAcceleration is set to 2, night time would move 8 times faster than normal.
      // An entire night would pass in 3 hours.
      serverNightTimeAcceleration = 1;
  
      // Persistent Time (value 0-1)// The actual server time is saved to storage, so when active, the next server start will use the saved time value.
      serverTimePersistent = 0;
  
      // SERVER SECURITY/ANTI HACK
  
      // Verifies .pbos against .bisign files. (only 2 is supported)
      verifySignatures = 2;
  
      // When enabled, the server will allow the connection only to clients with same the .exe revision as the server (value 0-1)
      forceSameBuild = 1;
  
      // Communication protocol used with game server (use only number 1)
      guaranteedUpdates = 1;
  
      // enable speedhack detection, values 1-10 (1 strict, 10 benevolent, can be float)
      speedhackDetection = 5;
  
      // The number of players concurrently processed during the login process. Should prevent massive performance drop during connection when a lot of people are connecting at the same time.
      loginQueueConcurrentPlayers = 5;
  
      // The maximum number of players that can wait in login queue
      loginQueueMaxPlayers = 500;
  
      // Max ping value until server kick the user (value in milliseconds)
      maxPing = 200;
  
      // DayZ server instance id, to identify the number of instances per box and their storage folders with persistence files
      instanceId = 1;
  
      // Checks if the persistence files are corrupted and replaces corrupted ones with empty ones (value 0-1)
      storageAutoFix = 1;
  
      // Mission to load on server startup. <MissionName>.<TerrainName>
      class Missions
      {
              class DayZ
              {
                      template = "dayzOffline.chernarusplus";
              };
      };

    # linux gsm config
    gsm: |
      ##################################
      ######## Default Settings ########
      ##################################
      # DO NOT EDIT, ANY CHANGES WILL BE OVERWRITTEN!
      # Copy settings from here and use them in either:
      # common.cfg - applies settings to every instance.
      # [instance].cfg - applies settings to a specific instance.
      
      #### Game Server Settings ####
      
      ## SteamCMD Login | https://docs.linuxgsm.com/steamcmd#steamcmd-login
      steamuser="username"
      steampass='password'
      
      ## Predefined Parameters | https://docs.linuxgsm.com/configuration/start-parameters
      ip="0.0.0.0"
      port="2302"
      
      ## DayZ Modules
      # Add mods with relative paths:
      # mods/@cf
      # To load the "Community framework for DayZ SA" module found in the
      # directory serverfiles/mods/@cf.  Load several mods as:
      # mods="mods/@cf\;mods/@dayz-expansion\;mods/@deerisle"
      mods=""
      
      ## Server-side Mods
      servermods=""
      
      ## Path to BattlEye
      # Leave empty for default
      bepath=""
      
      ## Server Parameters | https://docs.linuxgsm.com/configuration/start-parameters#additional-parameters
      startparameters="-ip=${ip} -port=${port} -config=${servercfgfullpath} -mod=${mods} -servermod=${servermods} -bepath=${bepath} -limitFPS=60 -dologs -adminlog -freezeCheck"
      
      #### LinuxGSM Settings ####
      
      ## LinuxGSM Stats
      # Send useful stats to LinuxGSM developers.
      # https://docs.linuxgsm.com/configuration/linuxgsm-stats
      # (on|off)
      stats="off"
      
      ## Notification Alerts
      # (on|off)
      
      # Display IP | https://docs.linuxgsm.com/alerts#display-ip
      displayip=""
      
      # More info | https://docs.linuxgsm.com/alerts#more-info
      postalert="off"
      
      # Alert on Start/Stop/Restart
      statusalert="off"
      
      # Discord Alerts | https://docs.linuxgsm.com/alerts/discord
      discordalert="off"
      discordwebhook="webhook"
      
      # Email Alerts | https://docs.linuxgsm.com/alerts/email
      emailalert="off"
      email="email@example.com"
      emailfrom=""
      
      # Gotify Alerts | https://docs.linuxgsm.com/alerts/gotify
      gotifyalert="off"
      gotifytoken="token"
      gotifywebhook="webhook"
      
      # IFTTT Alerts | https://docs.linuxgsm.com/alerts/ifttt
      iftttalert="off"
      ifttttoken="accesstoken"
      iftttevent="linuxgsm_alert"
      
      # Pushbullet Alerts | https://docs.linuxgsm.com/alerts/pushbullet
      pushbulletalert="off"
      pushbullettoken="accesstoken"
      channeltag=""
      
      # Pushover Alerts | https://docs.linuxgsm.com/alerts/pushover
      pushoveralert="off"
      pushovertoken="accesstoken"
      pushoveruserkey="userkey"
      
      # Rocket.Chat Alerts | https://docs.linuxgsm.com/alerts/rocket.chat
      rocketchatalert="off"
      rocketchatwebhook="webhook"
      
      # Slack Alerts | https://docs.linuxgsm.com/alerts/slack
      slackalert="off"
      slackwebhook="webhook"
      
      # Telegram Alerts | https://docs.linuxgsm.com/alerts/telegram
      # You can add a custom cURL string eg proxy (useful in Russia) in "curlcustomstring".
      # For example "--socks5 ipaddr:port" for socks5 proxy see more in "curl --help".
      telegramapi="api.telegram.org"
      telegramalert="off"
      telegramtoken="accesstoken"
      telegramchatid=""
      curlcustomstring=""
      
      ## Updating | https://docs.linuxgsm.com/commands/update
      updateonstart="off"
      
      ## Backup | https://docs.linuxgsm.com/commands/backup
      maxbackups="4"
      maxbackupdays="30"
      stoponbackup="on"
      
      ## Logging | https://docs.linuxgsm.com/features/logging
      consolelogging="on"
      logdays="7"
      
      ## Monitor | https://docs.linuxgsm.com/commands/monitor
      # Query delay time
      querydelay="5"
      
      ## ANSI Colors | https://docs.linuxgsm.com/features/ansi-colors
      ansi="on"
      
      #### Advanced Settings ####
      
      ## Message Display Time | https://docs.linuxgsm.com/features/message-display-time
      sleeptime="0.5"
      
      ## SteamCMD Settings | https://docs.linuxgsm.com/steamcmd
      # Server appid
      appid="223350"
      steamcmdforcewindows="no"
      # SteamCMD Branch | https://docs.linuxgsm.com/steamcmd/branch
      branch=""
      betapassword=""
      # Master Server | https://docs.linuxgsm.com/steamcmd/steam-master-server
      steammaster="true"
      
      ## Stop Mode | https://docs.linuxgsm.com/features/stop-mode
      # 1: tmux kill
      # 2: CTRL+c
      # 3: quit
      # 4: quit 120s
      # 5: stop
      # 6: q
      # 7: exit
      # 8: 7 Days to Die
      # 9: GoldSrc
      # 10: Avorion
      # 11: end
      stopmode="2"
      
      ## Query mode
      # 1: session only
      # 2: gamedig (gsquery fallback)
      # 3: gamedig
      # 4: gsquery
      # 5: tcp
      querymode="2"
      querytype="protocol-valve"
      
      ## Console type
      consoleverbose="yes"
      consoleinteract="no"
      
      ## Game Server Details
      # Do not edit
      gamename="DayZ"
      engine="enfusion"
      glibc="2.27"
      
      #### Directories ####
      # Edit with care
      
      ## Game Server Directories
      systemdir="${serverfiles}"
      executabledir="${serverfiles}"
      executable="./DayZServer"
      servercfgdir="${systemdir}/cfg"
      servercfg="${selfname}.server.cfg"
      servercfgdefault="server.cfg"
      servercfgfullpath="${servercfgdir}/${servercfg}"
      
      ## Backup Directory
      backupdir="${lgsmdir}/backup"
      
      ## Logging Directories
      [ -n "${LGSM_LOGDIR}" ] && logdir="${LGSM_LOGDIR}" || logdir="${rootdir}/log"
      lgsmlogdir="${logdir}/script"
      consolelogdir="${logdir}/console"
      lgsmlog="${lgsmlogdir}/${selfname}-script.log"
      consolelog="${consolelogdir}/${selfname}-console.log"
      alertlog="${lgsmlogdir}/${selfname}-alert.log"
      postdetailslog="${lgsmlogdir}/${selfname}-postdetails.log"
      
      ## Logs Naming
      lgsmlogdate="${lgsmlogdir}/${selfname}-script-$(date '+%Y-%m-%d-%H:%M:%S').log"
      consolelogdate="${consolelogdir}/${selfname}-console-$(date '+%Y-%m-%d-%H:%M:%S').log"
      
      ## Log Parameters
      logtimestamp="off"
      logtimestampformat="%Y-%m-%d %H:%M:%S"